"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { PrismButton, HeroShimmer } from "@/components/glass-components";
import { Sparkles, ArrowRight } from "lucide-react";
import { DynamicLogo } from "@/components/DynamicLogo";
import { FacetClassForcer } from "@/components/force-facet-classes";
import { ParallaxGradient } from "@/components/ParallaxGradient";
import { useState, useEffect } from "react";

export default function HomeHeroSection() {
  const [mounted, setMounted] = useState(false);

  // We need to use useEffect to handle client-only rendering for the dynamic interactive elements
  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <section className="relative overflow-hidden py-20 md:py-32">
      {/* Interactive background effect - client-side only */}
      {mounted && <ParallaxGradient className="absolute inset-0 z-0" />}

      {/* Hero content */}
      <div className="container relative z-10">
        <div className="mx-auto max-w-4xl text-center">
          {/* This ensures all facet classes are generated by Tailwind */}
          <FacetClassForcer />

          <div className="flex justify-center mb-8">
            {mounted ? (
              <DynamicLogo
                size="lg"
                className="opacity-90 transition-all duration-1000"
              />
            ) : (
              <div className="h-[150px] w-[150px]"></div> // Placeholder when not mounted
            )}
          </div>

          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl mb-6">
            <span className="relative">
              <HeroShimmer />
              <span className="relative">Meta-Prism</span>
            </span>
            <span className="block">Worldview Explorer</span>
          </h1>

          <p className="mb-10 text-xl text-muted-foreground md:text-2xl">
            Map your metaphysical signature across seven facets of reality
          </p>

          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link href="/assessment">
              <PrismButton size="lg" className="h-14 px-8">
                <Sparkles className="mr-2 h-5 w-5" />
                Begin Assessment
                <ArrowRight className="ml-2 h-5 w-5" />
              </PrismButton>
            </Link>
            <Link href="/about">
              <Button variant="outline" size="lg" className="h-14 px-8">
                Learn More
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
